version: "3.7"
services:
    frontend:
      container_name: frontend-graph
      image: dzulfikarindzar/jenkins:master
      ports: 
          - "8789:80"
      networks: 
          - netku
      environment:
          - VUE_APP_USERS=http://graphkitchen.host/api/users
          - VUE_APP_AUTH=http://graphkitchen.host/api/auth
          - VUE_APP_PRODUCT=http://graphkitchen.host/api/product
          - VUE_APP_CATEGORY=http://graphkitchen.host/api/category
          - VUE_APP_HISTORY=http://graphkitchen.host/api/history
          - VUE_APP_SEARCH=http://graphkitchen.host/api/product/search
          - VUE_APP_URL=http://graphkitchen.host/
          - VUE_APP_SORT=http://graphkitchen.host/api/product/sort


networks: 
    netku:
        driver: bridge