version: "3.7"
services:
    frontend:
      container_name: frontend
      image: dzulfikarindzar/jenkins:master
      ports: 
          - "8789:80"
      networks: 
          - netku
      environment:
          - VUE_APP_USERS=http://3.83.153.65/api/users
          - VUE_APP_AUTH=http://3.83.153.65/api/auth
          - VUE_APP_PRODUCT=http://3.83.153.65/api/product
          - VUE_APP_CATEGORY=http://3.83.153.65/api/category
          - VUE_APP_HISTORY=http://3.83.153.65/api/history
          - VUE_APP_SEARCH=http://3.83.153.65/api/product/search
          - VUE_APP_URL=http://3.83.153.65/
          - VUE_APP_SORT=http://3.83.153.65/api/product/sort


networks: 
    netku:
        driver: bridge